### ISSUE TITLE
`version.draft` should not be a list

### ISSUE THREAD

**Issue by strogonoff** [ietf-tools/relaton-data-ids#17]
Regarding: https://github.com/ietf-ribose/relaton-data-ids/blob/7e90bafefe9b579ddfa339169d5ffbe949e548f1/data/draft-3k1n-6tisch-alice0-00.yaml#L90-L92

According to the model, `version.draft` can contain either one string or nothing: https://github.com/relaton/relaton-models/blob/f3363d495c7da9987fd2eb91a5c958284cfb43c3/models/VersionInfo.lutaml#L10-L14

Unless we foresee a change which makes `version.draft` eligible for multiple values, we should not use a list for that probably.

Upstream https://github.com/relaton/relaton-ietf/issues/84

**Comment by strogonoff** [comment]
`version` spec was updated:
- there can now be [more than one `version`](https://github.com/relaton/relaton-models/blob/fee9ea8205756163a1d96de47f9b105dc701d8a0/models/BibliographicItem.lutaml#L58-L62), so it’s a list
- `version.draft` is at most one value, so not a list

**Comment by ronaldtse** [comment]
@andrew2net this is an urgent issue that blocks the usage of the bibxml-service. Can you proceed with the fix ASAP? Thanks!

**Comment by andrew2net** [comment]
@strogonoff can we close this issue?

**Comment by rjsparks** [comment]
@strogonoff - I'm closing this - re-open it if something still needs to be done.
