### ISSUE TITLE
`forename.content` should not be a list

### ISSUE THREAD

**Issue by stefanomunarini** [ietf-tools/relaton-data-ids#23]
Regarding https://github.com/ietf-tools/relaton-data-ids/blob/51819883fa002990c8cb638242ebe5ee9b60dc56/data/draft--pale-email-00.yaml#L30 and based on the [specs](https://github.com/relaton/relaton-models/blob/main/models/Forename.lutaml#L5),

`forename.content` should be a single instance of LocalizedString, and not a list.

**Comment by stefanomunarini** [comment]
Not sure who to tag/assign here, perhaps @andrew2net ?

**Comment by andrew2net** [comment]
@stefanomunarini the Relaton YAML doesn't match the diagram literally. In the example, you see a list of forenames, not content. Forename contains LocalizedString and optional initial string. LoclalizedString has its own content attribute. It's not the same content as you see in the spec. In the example, there are 2 forenames.
https://github.com/ietf-tools/relaton-data-ids/blob/51819883fa002990c8cb638242ebe5ee9b60dc56/data/draft--pale-email-00.yaml#L29-L35

**Comment by stefanomunarini** [comment]
Thanks for the clarification @andrew2net . That's correct, I misinterpreted the YAML. Closing this issue
